dataset:
  dataset_label: Long LFMC Viewer 3857
  local_dataset_path: /scratch/users/trobinet/long_lfmc/final_lfmc/lfmc_model/viewer_3857/lfmc_maps_3857.zarr
  grid_crs: EPSG:3857
  landcover_variable: dominant_landcover_code
  initial_date: 2024-12-31
  dates:
    - 2024-12-31

output:
  asset_root: /scratch/users/trobinet/long_lfmc/final_lfmc/lfmc_model/viewer_assets/web_mercator_3857
  manifest_filename: manifest.json
  clear_output_root: true

tiles:
  tile_size: 512
  min_zoom: 0
  max_zoom: 3
  extra_view_resolutions:
    - 250.0
    - 125.0
    - 62.5
    - 31.25
    - 15.625
    - 7.8125

rendering:
  default_valid_alpha: 191
  evergreen_forest_alpha: 30

layers:
  mean:
    variable: lfmc_ens_mean
    label: LFMC
    unit: percent
    min: 40.0
    max: 220.0
    palette:
      - [109, 39, 27]
      - [202, 126, 74]
      - [208, 196, 135]
      - [109, 142, 96]
      - [37, 59, 54]
    stops: [0.0, 0.18, 0.40, 0.68, 1.0]
