ensemble:
  outputs_root: /scratch/users/trobinet/long_lfmc/final_lfmc/lfmc_model/outputs/lfmc_vh_vv_365_ens
  input_data_name: ensemble/lfmc_vh_vv_365_ens
  inputs_root: /scratch/users/trobinet/long_lfmc/final_lfmc/lfmc_model/inputs
  fold: 9998
  fallback_num_tasks: 3
  model_type: standard

data:
  grid_path: /scratch/users/trobinet/long_lfmc/final_lfmc/grid/epsg5070_500m_westUS_grid.nc4
  requested_start_date: 2024-01-01
  requested_end_date: 2024-12-31

paths:
  run_root: /scratch/users/trobinet/long_lfmc/final_lfmc/lfmc_model/inference/map_runs/lfmc_vh_vv_365_ens
  tile_metadata_subdir: tile_metadata
  prepared_subdir: prepared_tensors
  shard_subdir: shards
  merged_subdir: merged
  merged_store_name: lfmc_maps.zarr
  validation_subdir: validation
  plots_subdir: plots

chunking:
  tile_size: 10
  months_per_block: 1
  time_chunk_days: 31
  y_chunk: 256
  x_chunk: 256

submission:
  validation_test: true
  interactive_validation_pipeline: true
  forward_batch_size: 2056
  validation_site_n: 10
  max_tiles: 2
  array_concurrency: 32
  tasks_per_job: 5
  merge_blocks_per_job: 1
  use_gpu_forward: true
  gpu_fine_tasks_per_job: 5
  gpu_max_jobs: 8
  gpu_lock_dir: /scratch/users/trobinet/long_lfmc/final_lfmc/lfmc_model/gpu_locks
  gpu_submit_sleep_seconds: 30
  gpu_time_limit: 02:00:00
  gpu_cpus_per_task: 4
  gpu_mem: 32G
